### ISSUE TITLE
feat/group

### ISSUE THREAD

**Issue by sookyoungwoo** [soolung/simblue-client#101]
### ✨ Describe

그룹 등록 기능입니다.

### ✅ Tasks

- [ ] 그룹 페이지 구현
- 현재 그룹 목록
- 그룹추가 버튼

- [ ] 그룹 추가 모달
- 그룹 이름 입력란
- 그룹 유형 선택란

- [ ] 그룹 추가 페이지
- 추가할 학생 검색창
- 현재 추가된 학생 목록
