### ISSUE TITLE
필수 응답 여부 지정

### ISSUE THREAD

**Issue by gimhanul** [soolung/simblue-client#42]
### ✨ Describe

각 항목별로 필수 응답 여부를 지정할 수 있어야 합니다.

### ✅ Tasks

- [x] 필수 응답 화면에 표시
- [x] 신청 만들 때 필수 응답 지정
- [x] api에 필수 응답 필드 추가
