### ISSUE TITLE
설명 필드 추가

### ISSUE THREAD

**Issue by gimhanul** [soolung/simblue-client#43]
### ✨ Describe

각 항목에 설명 필드를 추가해야 합니다.

### ✅ Tasks

- [ ] 신청 페이지에 설명 추가
- [x] 신청 만드는 페이지에 설명 추가
- [x] api에 설명 추가
